server:
 port: 80
eureka:
 client: # 客户端进行Eureka注册的配置
  service-url:
   defaultZone: http://localhost:7001/eureka
 instance:
  instance-id: microcloud-provider-consumer
  prefer-ip-address: true
spring:
  application:
   name: microcloud-provider-consumer